#include "synonyms.h"

Phrase phrases[] = {
    {"Break the ice", {" Start a conversation", " Ease the tension", " Get things going", " Initiate talk", " Kick things off"}, 5, 3},
    {"Hit the sack", {" Go to bed", " Sleep", " Turn in", " Crash", " Call it a night"}, 5, 3},
    {"Under the weather", {" Feeling sick", " Not well", " Ill", " Slightly unwell", " Out of sorts"}, 5, 3},
    {"Spill the beans", {" Reveal a secret", " Let it slip", " Disclose info", " Tell the truth", " Divulge"}, 5, 3},
    {"Let the cat out of the bag", {" Reveal a secret", " Spill the beans", " Expose", " Tell by accident", " Let it slip"}, 5, 7},
    {"Once in a blue moon", {" Very rarely", " Hardly ever", " Infrequently", " Almost never", " Occasionally"}, 5, 6},
    {"Piece of cake", {" Very easy", " A breeze", " No sweat", " Simple task", " Easy peasy"}, 5, 3},
    {"Costs an arm and a leg", {" Very expensive", " Overpriced", " Exorbitant", " Costly", " High-priced"}, 5, 6},
    {"Burn the midnight oil", {" Work late", " Stay up working", " Work overtime", " Work into the night", " Study late"}, 5, 4},
    {"Hit the nail on the head", {" Be exactly right", " Get it right", " Identify correctly", " Accurately describe", " Nail it"}, 5, 6},
    {"Bite the bullet", {" Face the difficulty", " Endure pain", " Tough it out", " Deal with it", " Take it head-on"}, 5, 4},
    {"Kill two birds with one stone", {" Achieve two things at once", " Double benefit", " Two results in one go", " Do two jobs together", " Be efficient"}, 5, 7},
    {"The ball is in your court", {" It's your decision", " You must decide", " It's up to you", " Your move", " You're in charge now"}, 5, 7},
    {"Wrap your head around", {" Understand", " Grasp", " Comprehend", " Get it", " Make sense of"}, 5, 4},
    {"Let someone off the hook", {" Forgive", " Not punish", " Pardon", " Excuse", " Release from blame"}, 5, 6},
    {"Pull someone's leg", {" Joke", " Tease", " Kid", " Playfully deceive", " Make fun"}, 5, 3},
    {"Sit on the fence", {" Undecided", " Neutral", " Not choosing sides", " Hesitate", " Non-committal"}, 5, 4},
    {"Throw in the towel", {" Give up", " Surrender", " Quit", " Admit defeat", " Back down"}, 5, 4},
    {"Under your nose", {" In plain sight", " Right there", " Obvious", " Easily visible", " Right in front of you"}, 5, 3},
    {"Get cold feet", {" Lose courage", " Get nervous", " Back out", " Feel unsure", " Second guess"}, 5, 3},
    {"Go the extra mile", {" Put in more effort", " Exceed expectations", " Work harder", " Do more", " Overdeliver"}, 5, 4},
    {"Cut to the chase", {" Get to the point", " Be direct", " Skip the details", " Be concise", " Speak plainly"}, 5, 4},
    {"On thin ice", {" In a risky position", " At risk", " In danger", " Walking a fine line", " Vulnerable"}, 5, 3},
    {"Bend over backwards", {" Go out of your way", " Try really hard", " Do everything possible", " Make a big effort", " Do your utmost"}, 5, 3},
    {"Hit the books", {" Study hard", " Prepare for exams", " Review material", " Crack the books", " Study intensely"}, 5, 3},
    {"Blow off steam", {" Release stress", " Vent", " Unwind", " Relax", " Let it out"}, 5, 3},
    {"In hot water", {" In trouble", " In a mess", " In a bad situation", " Facing consequences", " In difficulty"}, 5, 3},
    {"Keep your chin up", {" Stay positive", " Be strong", " Don't give up", " Stay hopeful", " Hang in there"}, 5, 4},
    {"Cry over spilled milk", {" Regret the past", " Complain about a loss", " Mourn over what's done", " Feel sorry unnecessarily", " Dwell on it"}, 5, 4},
    {"Beat around the bush", {" Avoid the point", " Be indirect", " Evade", " Not get to the point", " Circle the topic"}, 5, 4},
    {"Barking up the wrong tree", {" Accuse wrongly", " Misjudge", " Wrongly blame", " Make a false assumption", " Be mistaken"}, 5, 6},
    {"Best of both worlds", {" Advantages of both", " Ideal situation", " Perfect balance", " Double benefit", " Win-win"}, 5, 5},
    {"By the skin of your teeth", {" Barely", " Just in time", " Narrowly", " Almost missed", " Just made it"}, 5, 6},
    {"Call it a day", {" Stop working", " Quit for now", " Finish up", " Wrap up", " End work"}, 5, 4},
    {"Cut corners", {" Do something poorly", " Take shortcuts", " Save effort", " Skimp", " Avoid work"}, 5, 2},
    {"Devil's advocate", {" Oppose for argument's sake", " Challenge ideas", " Question assumptions", " Play skeptic", " Argue the opposite"}, 5, 2},
    {"Don't count your chickens", {" Don't assume", " Wait for results", " Don't be premature", " Don't get ahead", " Be cautious"}, 5, 4},
    {"Every cloud has a silver lining", {" Look for the good", " Positive side", " Hope in bad times", " Good from bad", " Optimistic view"}, 5, 7},
    {"Give someone the cold shoulder", {" Ignore", " Shun", " Avoid", " Snub", " Turn away"}, 5, 5},
    {"Go down in flames", {" Fail spectacularly", " Crash and burn", " Mess up badly", " Fall apart", " Flop"}, 5, 4},
    {"Hit the road", {" Leave", " Start a journey", " Go away", " Set off", " Depart"}, 5, 3},
    {"In the same boat", {" In a similar situation", " Together", " Sharing the problem", " Same condition", " Jointly involved"}, 5, 4},
    {"It takes two to tango", {" Both responsible", " Both involved", " Shared blame", " Mutual effort", " Cooperation needed"}, 5, 6},
    {"Jump on the bandwagon", {" Join trend", " Follow others", " Do what's popular", " Get on board", " Follow crowd"}, 5, 4},
    {"Keep an eye on", {" Watch closely", " Monitor", " Observe", " Pay attention", " Look after"}, 5, 4},
    {"Let sleeping dogs lie", {" Avoid trouble", " Don't stir problems", " Leave things alone", " Don't reopen issues", " Stay out of it"}, 5, 4},
    {"Make a long story short", {" Be brief", " Summarize", " Get to the point", " Skip details", " Tell briefly"}, 5, 5},
    {"Miss the boat", {" Miss an opportunity", " Be too late", " Fail to act", " Lose chance", " Not catch up"}, 5, 3},
    {"No pain, no gain", {" Effort needed", " Hard work required", " Suffer for success", " Work for results", " Earn by effort"}, 5, 4},
    {"the best of both worlds", {" advantages of both", " ideal situation", " perfect balance", " double benefit", " win-win"}, 5, 5},
    {"the last straw", {" final problem", " breaking point", " limit reached", " last annoyance", " ultimate irritation"}, 5, 3},
    {"throw in the towel", {" give up", " surrender", " quit", " admit defeat", " back down"}, 5, 4},
    {"under the gun", {" under pressure", " in a hurry", " under stress", " facing deadline", " in a tight spot"}, 5, 3},
    {"up in the air", {" uncertain", " undecided", " unresolved", " not settled", " pending"}, 5, 4},
    {"water under the bridge", {" past and forgiven", " no longer important", " old history", " forget past", " irrelevant now"}, 5, 4},
    {"impossible", {" never", " when pigs fly", " will not happen", " unrealistic", " no chance"}, 5, 1},
    {"you can't judge a book by its cover", {" don't judge superficially", " appearances deceive", " look deeper", " don't assume", " know more first"}, 5, 8},
    {"How are you?", {"What's up?", "How's it going?", "How do you do?", "How have you been?", "What's going on?"}, 5},
    {"Thank you", {"Thanks", "Many thanks", "Much appreciated", "Thanks a lot", "I appreciate it"}, 5},
    {"You're welcome", {"No problem", "Anytime", "Don't mention it", "Glad to help", "Sure thing"}, 5},
    {"I don't know", {"Not sure", "No idea", "I have no clue", "I can't say", "Beats me"}, 5},
    {"I’m sorry", {"My apologies", "Pardon me", "Excuse me", "Forgive me", "I regret that"}, 5},
    {"See you later", {"Catch you later", "Talk to you soon", "See ya", "Until next time", "Take care"}, 5},
    {"Good morning", {"Morning", "Top of the morning", "Rise and shine", "Hello in the morning", "Wishing you a good morning"}, 5},
    {"Good night", {"Sweet dreams", "Sleep well", "Nighty night", "Rest well", "Have a good night"}, 5},
    {"Good luck", {"Best of luck", "All the best", "Break a leg", "Fingers crossed", "Wishing you success"}, 5},
    {"Congratulations", {"Well done", "Nice job", "Good going", "Kudos", "Hats off"}, 5},

    {"Take care", {"Be careful", "Stay safe", "Look after yourself", "Be well", "Mind yourself"}, 5},
    {"Hurry up", {"Get a move on", "Move quickly", "Rush", "Step on it", "Come on"}, 5},
    {"Calm down", {"Relax", "Take it easy", "Chill out", "Simmer down", "Cool it"}, 5},
    {"What do you mean?", {"Can you explain?", "What are you saying?", "Clarify that", "I don’t get it", "Be more specific"}, 5},
    {"I agree", {"You're right", "Exactly", "Totally", "Absolutely", "I feel the same"}, 5},
    {"I disagree", {"Not quite", "I don't think so", "Not really", "I’m not sure about that", "I beg to differ"}, 5},
    {"That's right", {"Exactly", "Correct", "You got it", "True", "That's it"}, 5},
    {"That’s wrong", {"Incorrect", "Nope", "Not quite", "That's not right", "False"}, 5},
    {"Excuse me", {"Pardon me", "Sorry", "Sorry to interrupt", "I beg your pardon", "May I?"}, 5},
    {"Never mind", {"Forget it", "It’s okay", "No worries", "Don’t bother", "Let it go"}, 5},

    {"I’m tired", {"I’m exhausted", "I’m beat", "I’m worn out", "I’m drained", "I need rest"}, 5},
    {"I’m hungry", {"I need food", "I’m starving", "I’m famished", "I could eat", "I’m ravenous"}, 5},
    {"Just a moment", {"Hold on", "Give me a second", "Wait a minute", "One sec", "Hang on"}, 5},
    {"I’m busy", {"I’m tied up", "I’ve got a lot to do", "I’m occupied", "I’m swamped", "I’m slammed"}, 5},
    {"Let’s go", {"Come on", "Time to move", "Let’s move", "We should leave", "Let's head out"}, 5},
    {"What’s your name?", {"Who are you?", "May I know your name?", "Tell me your name", "Can I have your name?", "What do they call you?"}, 5},
    {"I love you", {"I adore you", "I'm in love with you", "I care deeply about you", "I cherish you", "You mean everything to me"}, 5},
    {"I need help", {"Can you assist me?", "Help me out", "I could use a hand", "Give me a hand", "I need assistance"}, 5},
    {"It doesn’t matter", {"No big deal", "It’s okay", "Don’t worry about it", "Forget it", "It's not important"}, 5},
    {"I don’t mind", {"That’s fine", "It’s okay", "No problem", "I’m okay with it", "I have no objection"}, 5},
    {"Long time no see", {"It’s been a while", "Haven’t seen you in ages", "It’s been forever", "Nice to see you again", "Where have you been?"}, 5},
    {"Take it easy", {"Calm down", "Relax", "No stress", "Chill out", "Don’t overdo it"}, 5},
    {"It’s up to you", {"Your choice", "You decide", "Do as you like", "Whatever you want", "It’s your call"}, 5},
    {"Make yourself at home", {"Feel free", "Get comfortable", "Relax here", "Feel at ease", "You’re welcome here"}, 5},
    {"Let me know", {"Tell me", "Inform me", "Keep me posted", "Update me", "Fill me in"}, 5},

    {"I’ll be right back", {"Be back soon", "Give me a minute", "I’m coming", "Back in a sec", "Hang tight"}, 5},
    {"Nice to meet you", {"Glad to meet you", "Pleased to meet you", "It’s a pleasure", "Happy to meet you", "Delighted to meet you"}, 5},
    {"What do you think?", {"Any thoughts?", "How do you feel about it?", "Your opinion?", "Got an idea?", "What’s your take?"}, 5},
    {"I think so", {"Probably", "I believe so", "Seems like it", "That’s likely", "I guess so"}, 5},
    {"I’m not sure", {"I don’t know", "I can’t say", "Maybe", "difficult to tell","Not certain","I am Unsure"}, 5},
    {"Be careful", {"Watch out", "Take care", "Be cautious", "Stay alert", "Mind your step"}, 5},
    {"Come here", {"Get over here", "Come closer", "Approach", "Move this way", "Step up"}, 5},
    {"Go ahead", {"Do it", "Feel free", "Proceed", "You may", "Be my guest"}, 5},
    {"Get well soon", {"Feel better", "Hope you recover fast", "Take care", "Wishing you healing", "Speedy recovery","recover soon"}, 6},
    {"Bless you",{"God bless you", "Good health", "Be well", "Take care", "Stay blessed"}, 5},

    {"Have a good day", {"Enjoy your day", "Take care", "Hope your day goes well", "Have a nice one", "Wish you well"}, 5},
    {"No way", {"Absolutely not", "Not happening", "Out of the question", "I refuse", "Not a chance"}, 5},
    {"Of course", {"Sure", "Definitely", "Yes", "Absolutely", "Without a doubt"}, 5},
    {"Not yet", {"Still waiting", "Not now", "Soon", "In a while", "Maybe later"}, 5},
    {"I’m coming", {"On my way", "Be there soon", "Heading over", "Coming now", "Approaching"}, 5},
    {"What’s wrong?", {"What happened?", "What’s the matter?", "What’s the issue?", "Are you okay?", "Why the long face?"}, 5},
    {"Let’s do it", {"Let's go for it", "I'm in", "Count me in", "Sounds good", "Let's make it happen"}, 5},
    {"Just kidding", {"Only joking", "Just messing with you", "Playing around", "Don’t take it seriously", "It’s a joke"}, 5},
    {"I’m afraid so", {"Yes, unfortunately", "I think so", "Sadly, yes", "That’s true", "Looks like it"}, 5},
    {"I’m afraid not", {"No, sorry", "Sadly, no", "I don’t think so", "Unfortunately not", "That’s not the case"}, 5},

    {"Why not?", {"What’s stopping us?", "Sounds good", "Let’s do it", "No reason not to", "Sure"}, 5},
    {"That's interesting", {"Fascinating", "That's cool", "Really?", "That’s surprising", "Oh wow"}, 5},
    {"I understand", {"I get it", "Gotcha", "I follow", "Makes sense", "Okay"}, 5},
    {"It depends", {"Maybe", "Sometimes", "Possibly", "That varies", "Not always"}, 5},
    {"Let’s see", {"Let me think", "Hmm", "Checking", "Wait a moment", "Let's figure this out"}, 5},
    {"That's true", {"Exactly", "Correct", "You're right", "Indeed", "Absolutely"}, 5},
    {"I don’t believe it", {"No way", "Seriously?", "Are you kidding?", "That's crazy", "You must be joking"}, 5},
    {"It happens", {"That’s life", "Things happen", "Oh well", "No big deal", "Such is life"}, 5},
    {"Are you sure?", {"Really?", "Positive?", "Is that right?", "No doubt?", "You mean it?"}, 5},
    {"Just in case", {"For safety", "As a backup", "If needed", "In case of emergency", "To be safe"}, 5},

    {"By the way", {"Incidentally", "While we're at it", "Also", "Speaking of which", "On another note"}, 5},
    {"No problem", {"It’s okay", "Anytime", "Don’t worry", "Not an issue", "Sure thing"}, 5},
    {"Don’t worry", {"It’s all right", "Relax", "Everything’s fine", "No need to stress", "You’ll be okay"}, 5},
    {"I’ll think about it", {"Let me consider it", "I need time", "I'll get back to you", "I’m not sure yet", "I’ll decide soon"}, 5},
    {"What are you doing?", {"What’s up?", "What’s going on?", "What’s happening?", "What are you up to?", "How’s it going?"}, 5},
    {"Wait a moment", {"Hold on", "Give me a second", "Just a sec", "One moment", "Hang on"}, 5},
    {"Welcome back", {"Good to see you again", "You're back", "Glad you're here", "Nice to see you", "You've returned"}, 5},
    {"Do you need help?", {"Can I help you?", "Need assistance?", "Want a hand?", "Shall I help?", "Anything I can do?"}, 5},
    {"That makes sense", {"I get it", "Understandable", "That’s logical", "Sounds right", "That figures"}, 5},
    {"Can you repeat that?", {"Say it again", "I didn’t hear", "Come again?", "Could you repeat?", "Repeat, please"}, 5},
    {"Let’s take a break", {"Time for a rest", "Let’s pause", "Break time", "Rest a bit", "Short break"}, 5},
    {"Take your time", {"No rush", "At your own pace", "When you're ready", "Don't hurry", "Go slow"}, 5},
    {"Nice work", {"Good job", "Well done", "Impressive", "Awesome", "Great effort"}, 5},
    {"You’re amazing", {"You're awesome", "You’re incredible", "You rock", "You're fantastic", "You’re the best"}, 5},
    {"Everything will be okay", {"Things will work out", "It’ll be fine", "Don’t worry", "Stay strong", "You’ll be alright"}, 5},
    {"Don’t give up", {"Keep going", "Hang in there", "Stay strong", "Push through", "Keep trying"}, 5},
    {"I got it", {"Understood", "I see", "I understand", "Okay", "All right"}, 5},
    {"No thanks", {"I’m good", "Not right now", "Maybe later", "I’ll pass", "Thanks anyway"}, 5},
    {"That’s amazing", {"Wow", "Incredible", "Awesome", "Impressive", "Outstanding"}, 5},
    {"I’m on it", {"Working on it", "I’ve got this", "Handling it", "Doing it now", "Taking care of it"}, 5},
    {"Sounds good", {"Alright", "Okay", "Sure", "Fine by me", "I’m in"}, 5},
    {"Let’s keep in touch", {"Stay connected", "Don’t be a stranger", "Talk soon", "Message me later", "Reach out"}, 5},
    {"What’s the plan?", {"What are we doing?", "What’s next?", "Any idea?", "What’s happening?", "What’s the agenda?"}, 5},
    {"I miss you", {"Thinking of you", "Wish you were here", "Longing for you", "Can’t wait to see you", "You’re on my mind"}, 5},
    {"I don't care", {"Whatever", "It doesn’t bother me", "I’m indifferent", "Makes no difference", "I’m cool with it"}, 5},
    {"I'm not sure", {"I don’t know", "Can’t say", "Maybe", "Uncertain", "No idea"}, 5},
    {"Calm down", {"Take it easy", "Relax", "Chill out", "Settle down", "Cool off"}, 5},
    {"That's amazing", {"Awesome", "Impressive", "Incredible", "Fantastic", "Wonderful"}, 5},
    {"No way!", {"Seriously?", "Are you kidding?", "Unbelievable", "Impossible", "Really?"}, 5},
    {"You're right", {"Exactly", "True", "Correct", "Absolutely", "I agree"}, 5},
    {"That's wrong", {"Incorrect", "Not true", "Nope", "False", "I disagree"}, 5},
    {"Not at all", {"Nope", "Certainly not", "Absolutely not", "Never", "By no means"}, 5},
    {"Why not?", {"Sounds good", "Let’s do it", "What’s the harm?", "No reason not to", "Why wouldn’t we?"}, 5},
    {"I can't wait", {"So excited", "Looking forward to it", "Anticipating it", "Super eager", "Can’t stop thinking about it"}, 5},

    {"I’m done", {"Finished", "Completed", "That’s it", "All set", "Wrapped up"}, 5},
    {"No big deal", {"It’s nothing", "Not important", "No problem", "Don’t worry", "Forget it"}, 5},
    {"What’s going on?", {"What’s up?", "What’s happening?", "Anything new?", "What’s the situation?", "What’s the deal?"}, 5},
    {"Don’t be silly", {"That’s nonsense", "Come on", "Stop joking", "Be serious", "Don’t act like that"}, 5},
    {"I knew it", {"Told you", "I was right", "Just as I thought", "I expected that", "It was obvious"}, 5},
    {"It’s your turn", {"You go now", "Your move", "Go ahead", "Time for you", "Take your shot"}, 5},
    {"Are you ready?", {"Set to go?", "Prepared?", "Good to start?", "Shall we begin?", "Ready yet?"}, 5},
    {"Don’t worry about it", {"It’s fine", "No need to stress", "Forget it", "Let it go", "No problem"}, 5},
    {"I'll try", {"I’ll give it a shot", "Let me attempt", "I’ll make an effort", "I’ll see what I can do", "I'll do my best"}, 5},
    {"How’s everything?", {"How are things?", "All good?", "What’s up?", "How’s life?", "Everything okay?"}, 5},

    {"I'm busy", {"Tied up", "Occupied", "Swamped", "Engaged", "Have a lot on my plate"}, 5},
    {"Don’t forget", {"Remember", "Keep it in mind", "Don’t miss it", "Make sure you remember", "Stay aware"}, 5},
    {"I’m not interested", {"Not my thing", "No thanks", "I'll pass", "Not into it", "Doesn't appeal to me"}, 5},
    {"It’s my fault", {"I messed up", "My bad", "I take responsibility", "I’m to blame", "I goofed"}, 5},
    {"That's great", {"Awesome", "Fantastic", "Wonderful", "Excellent", "Terrific"}, 5},
    {"I’m fine", {"Doing well", "Okay", "All right", "Pretty good", "No problem"}, 5},
    {"I see", {"Got it", "Understood", "Okay", "I get it now", "Makes sense"}, 5},
    {"I’m listening", {"Go ahead", "I’m paying attention", "Tell me more", "I’m all ears", "I’m tuned in"}, 5},
    {"Hold on", {"Wait a second", "Just a moment", "Hang tight", "Give me a sec", "Stay there"}, 5},
    {"It’s up to you", {"Your decision", "You choose", "Whatever you like", "Your call", "As you wish"}, 5},

    {"Take a seat", {"Sit down", "Have a seat", "Please be seated", "Grab a chair", "Rest here"}, 5},
    {"It’s over", {"Finished", "Done", "Ended", "No more", "That’s it"}, 5},
    {"You never know", {"Anything could happen", "It’s unpredictable", "Could be", "You can’t tell", "Hard to say"}, 5},
    {"Do your best", {"Give it your all", "Try your hardest", "Put in effort", "Work hard", "Give it a shot"}, 5},
    {"No rush", {"Take your time", "Whenever you’re ready", "No pressure", "No hurry", "Go slow"}, 5},
    {"Watch out", {"Be careful", "Look out", "Heads up", "Stay alert", "Mind yourself"}, 5},
    {"That sounds fun", {"Cool", "Exciting", "I’d love that", "Nice idea", "Sounds good"}, 5},
    {"I appreciate it", {"Thanks a lot", "Many thanks", "Much obliged", "I’m grateful", "Cheers"}, 5},
    {"Anytime", {"You’re welcome", "No problem", "Happy to help", "Sure thing", "No worries"}, 5},
    {"Keep going", {"Continue", "Carry on", "Don’t stop", "Push forward", "Stay with it"}, 5},

    {"Let me help", {"I’ll assist", "Can I give you a hand?", "Allow me", "Need help?", "I’ll support you"}, 5},
    {"Be yourself", {"Don’t pretend", "Stay true", "Act naturally", "Just be you", "Keep it real"}, 5},
    {"I promise", {"You have my word", "I swear", "I'll make sure", "Believe me", "Guaranteed"}, 5},
    {"Don’t move", {"Stay still", "Freeze", "Hold your position", "Stop", "Remain where you are"}, 5},
    {"Please wait", {"Hold on", "One moment", "Give me a second", "Stay there", "Wait up"}, 5},
    {"It's not fair", {"Unjust", "That’s wrong", "I feel cheated", "Unbalanced", "That’s biased"}, 5},
    {"Take it slow", {"No rush", "Go steady", "Easy does it", "Careful now", "Move gently"}, 5},
    {"That's enough", {"Stop it", "No more", "Cut it out", "That’s plenty", "You’ve done enough"}, 5},
    {"I'm on my way", {"Coming now", "Heading there", "Be right there", "Almost there", "En route"}, 5},
    {"I can’t believe it", {"Unreal", "No way", "Seriously?", "Hard to accept", "You’re kidding"}, 5},

    {"That's a good idea", {"Great thought", "I like that", "Sounds smart", "Let’s do it", "That works"}, 5},
    {"Don’t mention it", {"You're welcome", "No big deal", "Glad to help", "Sure", "Anytime"}, 5},
    {"Let me check", {"Give me a moment", "Hold on", "I’ll find out", "Checking now", "Looking into it"}, 5},
    {"No worries", {"Don’t stress", "It’s fine", "All good", "No big deal", "Relax"}, 5},
    {"I’m almost done", {"Nearly finished", "Just about there", "Almost ready", "Wrapping up", "One last step"}, 5},
    {"Just a little", {"Not much", "Tiny bit", "Slightly", "A bit", "Hardly any"}, 5},
    {"I made a mistake", {"My fault", "I messed up", "Oops", "I goofed", "I did it wrong"}, 5},
    {"I’ll call you", {"Talk to you later", "Phone you soon", "Ring you up", "Contact you", "I’ll be in touch"}, 5},
    {"Try again", {"Give it another go", "Once more", "Do it again", "Try once more", "Have another shot"}, 5},
    {"Let’s start", {"Begin now", "Kick off", "Get going", "Start up", "Let’s begin"}, 5},

    {"I don’t feel well", {"I’m sick", "Not feeling great", "Feeling off", "Unwell", "Under the weather"}, 5},
    {"I’ll let you know", {"I’ll inform you", "I’ll tell you later", "Keep you posted", "Update you", "I’ll get back to you"}, 5},
    {"Do you understand?", {"Got it?", "Do you follow?", "Clear?", "Do you get it?", "Any questions?"}, 5},
    {"I’m looking for", {"Searching for", "Trying to find", "In search of", "On the hunt for", "Seeking"}, 5},
    {"That’s funny", {"Hilarious", "So amusing", "That’s a good one", "LOL", "You’re funny"}, 5},
    {"Go to bed", {"Time to sleep", "Get some rest", "Hit the hay", "Turn in", "Call it a night"}, 5},
    {"Wake up", {"Get out of bed", "Open your eyes", "Rise and shine", "Get moving", "Time to get up"}, 5},
    {"It's a secret", {"Don’t tell anyone", "Keep it quiet", "Hush hush", "Confidential", "Between us"}, 5},
    {"Come with me", {"Join me", "Follow me", "Let’s go together", "Walk with me", "Tag along"}, 5},
    {"You can do it", {"Believe in yourself", "I know you can", "Go for it", "Give it a try", "Stay confident"}, 5},
    // Phrases 201–300
    {"Not really", {"I don’t think so", "Not exactly", "Kind of", "Sort of", "More or less"}, 5},
    {"It’s possible", {"Maybe", "Could be", "Possibly", "Might happen", "There's a chance"}, 5},
    {"Don’t be afraid", {"Be brave", "You’ve got this", "Stay strong", "No fear", "Keep going"}, 5},
    {"I’m confused", {"Not sure", "Don’t understand", "Lost", "Puzzled", "Perplexed"}, 5},
    {"Don’t forget to", {"Remember to", "Make sure to", "Be sure to", "Keep in mind to", "Don’t skip"}, 5},
    {"Not bad", {"Pretty good", "Decent", "Okay", "Alright", "Could be worse"}, 5},
    {"It’s fine", {"All good", "No worries", "Don’t worry", "Everything’s okay", "It’s alright"}, 5},
    {"Come in", {"Enter", "Step inside", "Go in", "Walk in", "You’re welcome to come"}, 5},
    {"Let’s meet up", {"Let’s hang out", "Get together", "Catch up", "Meet later", "See each other"}, 5},
    {"I’ll be there", {"On my way", "Coming now", "See you soon", "Be there shortly", "Heading over"}, 5},

    {"Keep it up", {"Well done", "Nice work", "Continue like that", "Stay consistent", "Good going"}, 5},
    {"Good job", {"Well done", "Nice work", "Great effort", "Excellent", "Proud of you"}, 5},
    {"Get out", {"Leave", "Go away", "Exit", "Step out", "Move along"}, 5},
    {"Don’t be late", {"Be on time", "Hurry up", "Make it on time", "Don’t delay", "Be punctual"}, 5},
    {"That’s strange", {"Weird", "Odd", "Unusual", "Bizarre", "Peculiar"}, 5},
    {"Sounds interesting", {"I’d like to know more", "Tell me more", "That’s cool", "Looks fun", "Seems exciting"}, 5},
    {"Let’s fix it", {"We need to repair it", "Make it better", "Correct it", "Solve the problem", "Adjust it"}, 5},
    {"You were right", {"I agree now", "You were correct", "Turns out you were right", "Good point", "You nailed it"}, 5},
    {"I feel you", {"I understand", "I get it", "Been there", "Same here", "Totally relate"}, 5},
    {"I’m proud of you", {"Great job", "You did well", "Impressive", "Kudos", "Well deserved"}, 5},

    {"Don’t lie", {"Be honest", "Tell the truth", "Speak frankly", "No fibbing", "Say it straight"}, 5},
    {"I can’t help it", {"I have no control", "It’s not up to me", "I can’t resist", "I have to", "I’m powerless"}, 5},
    {"That’s enough for now", {"Let’s stop here", "Pause for now", "We’re done for now", "Take a break", "Time out"}, 5},
    {"Give me a break", {"Come on", "Seriously?", "Not fair", "Spare me", "You must be kidding"}, 5},
    {"What’s your opinion?", {"What do you think?", "How do you feel about it?", "Got any thoughts?", "Any input?", "What’s your take?"}, 5},
    {"Let’s try it", {"Give it a go", "Test it", "See how it works", "Try this", "Give it a shot"}, 5},
    {"That’s impressive", {"Wow", "Nice", "Well done", "Outstanding", "Incredible"}, 5},
    {"Don’t push it", {"Take it easy", "Back off", "Don’t overdo it", "Don’t go too far", "Easy now"}, 5},
    {"Please don’t", {"I’d rather you not", "Kindly stop", "Don’t do that", "I’m asking you not to", "Avoid that"}, 5},
    {"Wait for me", {"Hold up", "Don’t go without me", "Stay there", "Pause a bit", "Give me a moment"}, 5},

    {"Tell me more", {"Go on", "Continue", "What else?", "I’m listening", "Keep talking"}, 5},
    {"Not again", {"This keeps happening", "Seriously again?", "Here we go again", "Another one?", "Back at it"}, 5},
    {"I can’t stand it", {"It drives me crazy", "I hate it", "This is unbearable", "I can’t handle it", "I’m fed up"}, 5},
    {"No doubt", {"Absolutely", "For sure", "Definitely", "Without question", "Undoubtedly"}, 5},
    {"That’s risky", {"It’s dangerous", "Could be harmful", "Not safe", "Be cautious", "Might not end well"}, 5},
    {"Don't worry too much", {"Take it easy", "Don’t stress", "Relax a bit", "It’ll be okay", "Stay calm","stay relaxed"}, 6},
    {"You’re in trouble", {"You messed up", "You’re caught", "Bad move", "There’s a problem", "This isn’t good"}, 5},
    {"Is this a joke?", {"You can’t be serious", "Are you kidding?", "Really?", "Come on now", "For real?","It sounds wrong"}, 6},
    {"Give it back", {"Return it", "Hand it over", "Bring it back", "I want it back", "Put it back"}, 5},
    {"That’s better", {"Much improved", "Looks good now", "Big difference", "Way nicer", "This works"}, 5},
    // Phrases 201–500
    {"Not really", {"I don’t think so", "Not exactly", "Kind of", "Sort of", "More or less"}, 5},
    {"It’s possible", {"Maybe", "Could be", "Possibly", "Might happen", "There's a chance"}, 5},
    {"Don’t be afraid", {"Be brave", "You’ve got this", "Stay strong", "No fear", "Keep going"}, 5},
    {"I’m confused", {"Not sure", "Don’t understand", "Lost", "Puzzled", "Perplexed"}, 5},
    {"Don’t forget to", {"Remember to", "Make sure to", "Be sure to", "Keep in mind to", "Don’t skip"}, 5},
    {"Not bad", {"Pretty good", "Decent", "Okay", "Alright", "Could be worse"}, 5},
    {"It’s fine", {"All good", "No worries", "Don’t worry", "Everything’s okay", "It’s alright"}, 5},
    {"Come in", {"Enter", "Step inside", "Go in", "Walk in", "You’re welcome to come"}, 5},
    {"Let’s meet up", {"Let’s hang out", "Get together", "Catch up", "Meet later", "See each other"}, 5},
    {"I’ll be there", {"On my way", "Coming now", "See you soon", "Be there shortly", "Heading over"}, 5},

    {"Keep it up", {"Well done", "Nice work", "Continue like that", "Stay consistent", "Good going"}, 5},
    {"Good job", {"Well done", "Nice work", "Great effort", "Excellent", "Proud of you"}, 5},
    {"Get out", {"Leave", "Go away", "Exit", "Step out", "Move along"}, 5},
    {"Don’t be late", {"Be on time", "Hurry up", "Make it on time", "Don’t delay", "Be punctual"}, 5},
    {"That’s strange", {"Weird", "Odd", "Unusual", "Bizarre", "Peculiar"}, 5},
    {"Sounds interesting", {"I’d like to know more", "Tell me more", "That’s cool", "Looks fun", "Seems exciting"}, 5},
    {"Let’s fix it", {"We need to repair it", "Make it better", "Correct it", "Solve the problem", "Adjust it"}, 5},
    {"You were right", {"I agree now", "You were correct", "Turns out you were right", "Good point", "You nailed it"}, 5},
    {"I feel you", {"I understand", "I get it", "Been there", "Same here", "Totally relate"}, 5},
    {"I’m proud of you", {"Great job", "You did well", "Impressive", "Kudos", "Well deserved"}, 5},

    {"Don’t lie", {"Be honest", "Tell the truth", "Speak frankly", "No fibbing", "Say it straight"}, 5},
    {"I can’t help it", {"I have no control", "It’s not up to me", "I can’t resist", "I have to", "I’m powerless"}, 5},
    {"That’s enough for now", {"Let’s stop here", "Pause for now", "We’re done for now", "Take a break", "Time out"}, 5},
    {"Give me a break", {"Come on", "Seriously?", "Not fair", "Spare me", "You must be kidding"}, 5},
    {"What’s your opinion?", {"What do you think?", "How do you feel about it?", "Got any thoughts?", "Any input?", "What’s your take?"}, 5},
    {"Let’s try it", {"Give it a go", "Test it", "See how it works", "Try this", "Give it a shot"}, 5},
    {"That’s impressive", {"Wow", "Nice", "Well done", "Outstanding", "Incredible"}, 5},
    {"Don’t push it", {"Take it easy", "Back off", "Don’t overdo it", "Don’t go too far", "Easy now"}, 5},
    {"Please don’t", {"I’d rather you not", "Kindly stop", "Don’t do that", "I’m asking you not to", "Avoid that"}, 5},
    {"Wait for me", {"Hold up", "Don’t go without me", "Stay there", "Pause a bit", "Give me a moment"}, 5},

    {"Tell me more", {"Go on", "Continue", "What else?", "I’m listening", "Keep talking"}, 5},
    {"Not again", {"This keeps happening", "Seriously again?", "Here we go again", "Another one?", "Back at it"}, 5},
    {"I can’t stand it", {"It drives me crazy", "I hate it", "This is unbearable", "I can’t handle it", "I’m fed up"}, 5},
    {"No doubt", {"Absolutely", "For sure", "Definitely", "Without question", "Undoubtedly"}, 5},
    {"That’s risky", {"It’s dangerous", "Could be harmful", "Not safe", "Be cautious", "Might not end well"}, 5},
    {"Don't worry too much", {"Take it easy", "Don’t stress", "Relax a bit", "It’ll be okay", "Stay calm"}, 5},
    {"You’re in trouble", {"You messed up", "You’re caught", "Bad move", "There’s a problem", "This isn’t good"}, 5},
    {"Is this a joke?", {"You can’t be serious", "Are you kidding?", "Really?", "Come on now", "For real?"}, 5},
    {"Give it back", {"Return it", "Hand it over", "Bring it back", "I want it back", "Put it back"}, 5},
    {"That’s better", {"Much improved", "Looks good now", "Big difference", "Way nicer", "This works"}, 5},

    {"You're joking", {"You must be kidding", "No way", "Seriously?", "You can’t be serious", "That’s a joke, right?"}, 5},
    {"Don't take it personally", {"It’s not about you", "Don’t be offended", "Don’t feel bad", "No hard feelings", "It’s nothing personal"}, 5},
    {"It’s not a big deal", {"No worries", "Don’t stress", "It’s nothing serious", "Don’t sweat it", "It’s minor"}, 5},
    {"You scared me", {"You startled me", "That was unexpected", "I jumped", "You gave me a fright", "You surprised me"}, 5},
    {"Be quiet", {"Shush", "Keep it down", "Silence", "Lower your voice", "Stop talking"}, 5},
    {"Keep in mind", {"Remember", "Don’t forget", "Take note", "Bear in mind", "Be aware"}, 5},
    {"That’s not funny", {"Not amusing", "I didn’t laugh", "That's rude", "That's inappropriate", "Be serious"}, 5},
    {"What a pity", {"That’s too bad", "What a shame", "How unfortunate", "That’s sad", "I feel bad"}, 5},
    {"That's annoying", {"So irritating", "Really frustrating", "Gets on my nerves", "That bothers me", "It’s a pain"}, 5},
    {"I’m on break", {"Taking a rest", "Paused for now", "Not working now", "Short break", "On a break"}, 5},

    {"I’ve had enough", {"I’m done", "That’s it", "No more", "I can’t take it anymore", "Over it"}, 5},
    {"That’s insane", {"Crazy", "Unbelievable", "Ridiculous", "Wild", "Out of control"}, 5},
    {"Are you okay?", {"Is everything fine?", "You alright?", "How are you feeling?", "Anything wrong?", "Feeling okay?"}, 5},
    {"I’m not feeling well", {"I feel sick", "I’m under the weather", "I’m ill", "Not doing great", "I feel off"}, 5},
    {"I’m not sure about that", {"I have doubts", "I’m uncertain", "Maybe not", "I’m not convinced", "I question that"}, 5},
    {"It doesn’t look good", {"That’s not a good sign", "Seems bad", "Looks rough", "Not promising", "Looks serious"}, 5},
    {"I can’t help you", {"I’m unable to assist", "Sorry, no can do", "I wish I could", "Out of my hands", "Not in my power"}, 5},
    {"It’s none of your business", {"Stay out of it", "It’s private", "Don’t concern yourself", "That’s personal", "Mind your business"}, 5},
    {"Don’t touch that", {"Leave it alone", "Keep your hands off", "Step away", "Do not mess with that", "Don’t go near it"}, 5},
    {"Let’s talk later", {"We’ll speak soon", "Talk to you later", "Catch up later", "Chat later", "We'll discuss it soon"}, 5},

    {"This is serious", {"It’s important", "Not a joke", "It’s real", "Take it seriously", "This is no game"}, 5},
    {"It’s not working", {"It failed", "It’s broken", "Something’s wrong", "It doesn’t function", "It’s not doing anything"}, 5},
    {"Don't make excuses", {"Stop justifying", "No excuses", "Be honest", "Own it", "Stop avoiding responsibility"}, 5},
    {"What do you mean by that?", {"Explain yourself", "Clarify that", "Be specific", "What are you trying to say?", "Come again?"}, 5},
    {"Speak clearly", {"Talk plainly", "Don’t mumble", "Enunciate", "Say it clearly", "Be articulate"}, 5},
    {"This makes no sense", {"It’s confusing", "I don’t understand", "It’s illogical", "That’s unclear", "I’m lost"}, 5},
    {"Are you kidding me?", {"Seriously?", "You must be joking", "No way", "Unbelievable", "You can't be serious"}, 5},
    {"That's impossible", {"Can’t be done", "No way", "Out of the question", "Unrealistic", "Not going to happen"}, 5},
    {"It’s too late", {"The time has passed", "Can’t do it now", "We missed it", "Too much delay", "No longer possible"}, 5},
    {"What’s your problem?", {"Why are you upset?", "What’s wrong with you?", "What’s going on?", "What’s bothering you?", "Why the attitude?"}, 5},

    {"That’s not allowed", {"Forbidden", "Against the rules", "Not permitted", "You can’t do that", "It’s prohibited"}, 5},
    {"Can I help you?", {"Need assistance?", "How can I help?", "What can I do?", "Do you need anything?", "May I assist you?"}, 5},
    {"Stop that", {"Cut it out", "Knock it off", "Don’t do that", "Enough", "Quit it"}, 5},
    {"Try harder", {"Put in more effort", "Give it your all", "Work more", "Push yourself", "Don’t give up"}, 5},
    {"It’s not fair", {"That's unjust", "That’s biased", "So one-sided", "I feel cheated", "It’s wrong"}, 5},
    {"This is boring", {"I’m not interested", "So dull", "I’m falling asleep", "Unexciting", "Not engaging"}, 5},
    {"You’re too slow", {"Speed up", "Hurry up", "Faster please", "You’re taking too long", "Pick up the pace"}, 5},
    {"You're too loud", {"Lower your voice", "Quiet down", "Tone it down", "Be quieter", "Reduce the volume"}, 5},
    {"You're in the way", {"Move aside", "Let me pass", "Step aside", "Block removed", "Shift over"}, 5},
    {"That’s enough for now", {"Let’s stop here", "We’re done for now", "Take a break", "Pause", "That will do"}, 5},

    {"Let’s get started", {"Time to begin", "Start now", "Let’s go", "Begin the task", "Kick it off"}, 5},
    {"Do it now", {"Right away", "Immediately", "No delay", "Without waiting", "At once"}, 5},
    {"Don't forget to call me", {"Remember to call", "Ring me later", "Give me a call", "Stay in touch", "Call when free"}, 5},
    {"It’s getting late", {"We’re running out of time", "Time’s almost up", "It’s quite late", "Getting dark", "Better hurry","we should hurry"}, 6},
    {"Everything is fine", {"All good", "No issues", "It’s okay", "No problem", "Going well"}, 5},
    {"This isn’t helpful", {"Not useful", "No assistance", "Doesn’t help", "That’s unhelpful", "No benefit"}, 5},
    {"Don’t say that", {"Watch your words", "That’s not nice", "Be careful what you say", "Keep that to yourself", "Mind your words"}, 5},
    {"This way please", {"Come this way", "Follow me", "Right this way", "Step this direction", "Walk with me"}, 5},
    {"I'm in trouble", {"I’m stuck", "Got a problem", "I need help", "In a bad situation", "Things are bad"}, 5},
    {"You’re not listening", {"Pay attention", "Focus please", "Are you ignoring me?", "Hear me out", "Listen closely"}, 5},
    // Phrases 501–600
    {"What’s next?", {"What now?", "What comes after?", "And then?", "Next step?", "What do we do now?"}, 5},
    {"You're absolutely right", {"I agree 100%", "Spot on", "Exactly right", "You nailed it", "True that"}, 5},
    {"I’ll think about it", {"Let me consider", "I need to reflect", "I’ll get back to you", "Give me time", "I'll decide later"}, 5},
    {"Go for it", {"Do it", "Give it a shot", "Take the chance", "Try it out", "Why not?"}, 5},
    {"That’s how it is", {"That’s life", "So it goes", "It is what it is", "That’s reality", "Can’t change it"}, 5},
    {"You’ve got to be kidding", {"No way", "Seriously?", "Unbelievable", "That’s a joke", "Can’t be real"}, 5},
    {"Sorry about that", {"My apologies", "Didn’t mean it", "Excuse me", "Forgive me", "Pardon that"}, 5},
    {"It won’t happen again", {"I’ll be careful", "I’ll avoid it next time", "Won’t repeat", "It’s a one-time thing", "I’ll make sure"}, 5},
    {"Let’s celebrate", {"Time to party", "Rejoice", "Have a celebration", "Throw a party", "Cheer up"}, 5},
    {"I'm really tired", {"I’m exhausted", "So sleepy", "Completely worn out", "Need rest", "Out of energy"}, 5},

    {"It’s worth it", {"It pays off", "Good investment", "Deserves the effort", "Valuable", "A good idea"}, 5},
    {"Don’t give up", {"Keep going", "Stay strong", "Hang in there", "Push through", "Keep trying"}, 5},
    {"Take your time", {"No rush", "Go at your pace", "Be thorough", "Do it carefully", "Don’t hurry"}, 5},
    {"I didn’t expect that", {"That was surprising", "Didn’t see that coming", "Caught me off guard", "Out of the blue", "Unexpected"}, 5},
    {"It’s too expensive", {"Costs too much", "Overpriced", "Not affordable", "Too pricey", "Out of my budget"}, 5},
    {"You’re amazing", {"You rock", "So awesome", "Really impressive", "Great work", "Fantastic"}, 5},
    {"That’s clever", {"Smart", "Sharp thinking", "Ingenious", "Wise move", "Brilliant"}, 5},
    {"Let’s stay in touch", {"Keep in contact", "Don’t lose connection", "Talk soon", "Reach out", "Stay connected"}, 5},
    {"I have a question", {"Need to ask", "Got a query", "Can I ask something?", "I’m wondering", "Need clarification"}, 5},
    {"That’s the best part", {"Highlight", "Most enjoyable", "Favorite part", "Top moment", "What I like most"}, 5},

    {"It was my fault", {"I messed up", "My mistake", "I take the blame", "I’m responsible", "I admit it"}, 5},
    {"Let me handle it", {"I’ll take care of it", "Leave it to me", "I got this", "I’ll manage", "My responsibility"}, 5},
    {"Don’t overthink", {"Keep it simple", "Relax", "Don’t stress", "Don’t complicate things", "Let it flow"}, 5},
    {"That explains it", {"Now I see", "Makes sense now", "Got it", "That’s why", "Understood"}, 5},
    {"I’ve changed my mind", {"I decided differently", "I have a new opinion", "I think otherwise", "I reconsidered", "I’m going with something else"}, 5},
    {"Let’s go out", {"Head out", "Go outside", "Leave home", "Go somewhere", "Step out"}, 5},
    {"Can you help me?", {"Need your help", "Assist me please", "Give me a hand", "Lend support", "Could you aid me?"}, 5},
    {"I like that idea", {"Sounds good", "I’m in", "That’s a great plan", "I agree", "Nice thought"}, 5},
    {"You're welcome", {"No problem", "Anytime", "Glad to help", "It’s nothing", "Sure thing"}, 5},
    {"I’ll be right back", {"Back in a sec", "Hold on", "Give me a moment", "Just a minute", "I’ll return soon"}, 5},

    {"Let’s be honest", {"Truth time", "No lies", "Speak frankly", "Be real", "Tell the truth"}, 5},
    {"That’s ridiculous", {"So silly", "That’s nonsense", "Unbelievable", "Absurd", "Too much"}, 5},
    {"I made a mistake", {"My fault", "I was wrong", "Did it wrong", "Screwed up", "Error on my part"}, 5},
    {"Take a seat", {"Sit down", "Have a seat", "Please sit", "Be seated", "Relax there"}, 5},
    {"Make yourself at home", {"Feel comfortable", "Relax here", "You're welcome here", "Settle in", "Feel free"}, 5},
    {"Be right there", {"Coming now", "On my way", "Just a moment", "Hold on", "Be there soon"}, 5},
    {"Don't move", {"Stay still", "Hold your position", "Freeze", "Remain there", "Don’t shift"}, 5},
    {"You’ve done well", {"Good job", "Proud of you", "Great effort", "Nicely done", "That’s excellent"}, 5},
    {"I’ll take that", {"Let me get it", "I’ll have it", "That’s mine", "I’ll hold it", "I got this"}, 5},
    {"See you soon", {"Catch you later", "Talk soon", "Until next time", "Later", "Goodbye for now","bye"}, 5},
   



};

int PHRASE_DICT_SIZE = sizeof(phrases)/sizeof(phrases[0]);
