#include "synonyms.h"

Phrase phrases[] = {
    {"Break the ice", {" Start a conversation", " Ease the tension", " Get things going", " Initiate talk", " Kick things off"}, 5, 3},
    {"Hit the sack", {" Go to bed", " Sleep", " Turn in", " Crash", " Call it a night"}, 5, 3},
    {"Under the weather", {" Feeling sick", " Not well", " Ill", " Slightly unwell", " Out of sorts"}, 5, 3},
    {"Spill the beans", {" Reveal a secret", " Let it slip", " Disclose info", " Tell the truth", " Divulge"}, 5, 3},
    {"Let the cat out of the bag", {" Reveal a secret", " Spill the beans", " Expose", " Tell by accident", " Let it slip"}, 5, 7},
    {"Once in a blue moon", {" Very rarely", " Hardly ever", " Infrequently", " Almost never", " Occasionally"}, 5, 6},
    {"Piece of cake", {" Very easy", " A breeze", " No sweat", " Simple task", " Easy peasy"}, 5, 3},
    {"Costs an arm and a leg", {" Very expensive", " Overpriced", " Exorbitant", " Costly", " High-priced"}, 5, 6},
    {"Burn the midnight oil", {" Work late", " Stay up working", " Work overtime", " Work into the night", " Study late"}, 5, 4},
    {"Hit the nail on the head", {" Be exactly right", " Get it right", " Identify correctly", " Accurately describe", " Nail it"}, 5, 6},
    {"Bite the bullet", {" Face the difficulty", " Endure pain", " Tough it out", " Deal with it", " Take it head-on"}, 5, 4},
    {"Kill two birds with one stone", {" Achieve two things at once", " Double benefit", " Two results in one go", " Do two jobs together", " Be efficient"}, 5, 7},
    {"The ball is in your court", {" It's your decision", " You must decide", " It's up to you", " Your move", " You're in charge now"}, 5, 7},
    {"Wrap your head around", {" Understand", " Grasp", " Comprehend", " Get it", " Make sense of"}, 5, 4},
    {"Let someone off the hook", {" Forgive", " Not punish", " Pardon", " Excuse", " Release from blame"}, 5, 6},
    {"Pull someone's leg", {" Joke", " Tease", " Kid", " Playfully deceive", " Make fun"}, 5, 3},
    {"Sit on the fence", {" Undecided", " Neutral", " Not choosing sides", " Hesitate", " Non-committal"}, 5, 4},
    {"Throw in the towel", {" Give up", " Surrender", " Quit", " Admit defeat", " Back down"}, 5, 4},
    {"Under your nose", {" In plain sight", " Right there", " Obvious", " Easily visible", " Right in front of you"}, 5, 3},
    {"Get cold feet", {" Lose courage", " Get nervous", " Back out", " Feel unsure", " Second guess"}, 5, 3},
    {"Go the extra mile", {" Put in more effort", " Exceed expectations", " Work harder", " Do more", " Overdeliver"}, 5, 4},
    {"Cut to the chase", {" Get to the point", " Be direct", " Skip the details", " Be concise", " Speak plainly"}, 5, 4},
    {"On thin ice", {" In a risky position", " At risk", " In danger", " Walking a fine line", " Vulnerable"}, 5, 3},
    {"Bend over backwards", {" Go out of your way", " Try really hard", " Do everything possible", " Make a big effort", " Do your utmost"}, 5, 3},
    {"Hit the books", {" Study hard", " Prepare for exams", " Review material", " Crack the books", " Study intensely"}, 5, 3},
    {"Blow off steam", {" Release stress", " Vent", " Unwind", " Relax", " Let it out"}, 5, 3},
    {"In hot water", {" In trouble", " In a mess", " In a bad situation", " Facing consequences", " In difficulty"}, 5, 3},
    {"Keep your chin up", {" Stay positive", " Be strong", " Don't give up", " Stay hopeful", " Hang in there"}, 5, 4},
    {"Cry over spilled milk", {" Regret the past", " Complain about a loss", " Mourn over what's done", " Feel sorry unnecessarily", " Dwell on it"}, 5, 4},
    {"Beat around the bush", {" Avoid the point", " Be indirect", " Evade", " Not get to the point", " Circle the topic"}, 5, 4},
    {"Barking up the wrong tree", {" Accuse wrongly", " Misjudge", " Wrongly blame", " Make a false assumption", " Be mistaken"}, 5, 6},
    {"Best of both worlds", {" Advantages of both", " Ideal situation", " Perfect balance", " Double benefit", " Win-win"}, 5, 5},
    {"By the skin of your teeth", {" Barely", " Just in time", " Narrowly", " Almost missed", " Just made it"}, 5, 6},
    {"Call it a day", {" Stop working", " Quit for now", " Finish up", " Wrap up", " End work"}, 5, 4},
    {"Cut corners", {" Do something poorly", " Take shortcuts", " Save effort", " Skimp", " Avoid work"}, 5, 2},
    {"Devil's advocate", {" Oppose for argument's sake", " Challenge ideas", " Question assumptions", " Play skeptic", " Argue the opposite"}, 5, 2},
    {"Don't count your chickens", {" Don't assume", " Wait for results", " Don't be premature", " Don't get ahead", " Be cautious"}, 5, 4},
    {"Every cloud has a silver lining", {" Look for the good", " Positive side", " Hope in bad times", " Good from bad", " Optimistic view"}, 5, 7},
    {"Give someone the cold shoulder", {" Ignore", " Shun", " Avoid", " Snub", " Turn away"}, 5, 5},
    {"Go down in flames", {" Fail spectacularly", " Crash and burn", " Mess up badly", " Fall apart", " Flop"}, 5, 4},
    {"Hit the road", {" Leave", " Start a journey", " Go away", " Set off", " Depart"}, 5, 3},
    {"In the same boat", {" In a similar situation", " Together", " Sharing the problem", " Same condition", " Jointly involved"}, 5, 4},
    {"It takes two to tango", {" Both responsible", " Both involved", " Shared blame", " Mutual effort", " Cooperation needed"}, 5, 6},
    {"Jump on the bandwagon", {" Join trend", " Follow others", " Do what's popular", " Get on board", " Follow crowd"}, 5, 4},
    {"Keep an eye on", {" Watch closely", " Monitor", " Observe", " Pay attention", " Look after"}, 5, 4},
    {"Let sleeping dogs lie", {" Avoid trouble", " Don't stir problems", " Leave things alone", " Don't reopen issues", " Stay out of it"}, 5, 4},
    {"Make a long story short", {" Be brief", " Summarize", " Get to the point", " Skip details", " Tell briefly"}, 5, 5},
    {"Miss the boat", {" Miss an opportunity", " Be too late", " Fail to act", " Lose chance", " Not catch up"}, 5, 3},
    {"No pain, no gain", {" Effort needed", " Hard work required", " Suffer for success", " Work for results", " Earn by effort"}, 5, 4},
    {"the best of both worlds", {" advantages of both", " ideal situation", " perfect balance", " double benefit", " win-win"}, 5, 5},
    {"the last straw", {" final problem", " breaking point", " limit reached", " last annoyance", " ultimate irritation"}, 5, 3},
    {"throw in the towel", {" give up", " surrender", " quit", " admit defeat", " back down"}, 5, 4},
    {"under the gun", {" under pressure", " in a hurry", " under stress", " facing deadline", " in a tight spot"}, 5, 3},
    {"up in the air", {" uncertain", " undecided", " unresolved", " not settled", " pending"}, 5, 4},
    {"water under the bridge", {" past and forgiven", " no longer important", " old history", " forget past", " irrelevant now"}, 5, 4},
    {"impossible", {" never", " when pigs fly", " will not happen", " unrealistic", " no chance"}, 5, 1},
    {"you can't judge a book by its cover", {" don't judge superficially", " appearances deceive", " look deeper", " don't assume", " know more first"}, 5, 8}
};

int PHRASE_DICT_SIZE = sizeof(phrases)/sizeof(phrases[0]);
